# Generated by Django 4.1.1 on 2022-10-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxeak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matrikula', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=50)),
                ('modeloa', models.CharField(max_length=50)),
                ('kolorea', models.CharField(max_length=50)),
                ('alokatzeko_prezioa', models.CharField(max_length=50)),
            ],
        ),
    ]
