# Generated by Django 4.1.1 on 2022-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertsonak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=50)),
                ('abizena', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('alokagai_daukan_kotxearen_id', models.CharField(max_length=3)),
            ],
        ),
    ]
